language: C
sudo: required

os:
  - linux
  - osx

# whitelist
branches:
  only:
    - develop

notifications:
  email: false

before_install:
    - |
      if [ "$(uname)" = "Linux" ]; then
         apt-cache search gfortran 
         sudo apt-get install gfortran-4.8;
      fi
    - ./install-hdf.sh

before_script:
    - ./install-cgns.sh

script:
    - cd src
    - make
    - cd tests
    - make
    - make test
    - cd ../examples/fortran
    - make
    - make test
    - cd ../../Test_UserGuideCode/Fortran_code
    - make
    - make test
    - cd ../C_code
    - make
    - make test
    
