language: C
sudo: required

os:
  - linux
#  - osx

# whitelist
branches:
  only:
    - develop

notifications:
  email: false

before_install:
    - |
      if [ "$(uname)" = "Linux" ]; then 
         sudo apt-get install gfortran;
         sudo apt-get install libhdf5-serial-dev
      else
         ./install-hdf.sh
      fi
script:
    - ./install-cgns.sh
    - cd src
    - make
    - cd tests
    - make
    - make test