language: C

#sudo: false

# whitelist
branches:
  only:
    - develop

notifications:
  email: false

before_install:
    - ./install-hdf.sh
    - sudo apt-get install gfortran

install:
    - ./install-cgns.sh

script: make
    
#    - python setup.py build -f
#    - python setup.py test