osx_image: xcode8.1
language: C
sudo: required

#dist: trusty
#os:
#  - osx
#  - linux

# whitelist
branches:
  only:
    - develop

notifications:
  email: false

before_install:
    - |
      if [ "$(uname)" = "Linux" ]; then
         sudo apt-get update -qq;
         sudo apt-get install -qq gfortran;
      fi
    - test $(uname) = "Darwin" && brew update || true
    - test $(uname) = "Darwin" && brew tap homebrew/versions || true
    - test $(uname) = "Darwin" && brew install gcc6 || true

matrix:
   include:
     - os: linux
       compiler: gcc-4.9
       install: export CC="gcc" export FC="gfortran" export F77="gfortran"
     - os: osx
       compiler: /usr/local/Cellar/gcc6/6.2.0/bin/gcc-6
       install: export CC="/usr/local/Cellar/gcc6/6.2.0/bin/gcc-6" export FC="/usr/local/Cellar/gcc6/6.2.0/bin/gfortran-6" export F77="/usr/local/Cellar/gcc6/6.2.0/bin/gfortran-6"

before_script:
    - ./bin/install-hdf.sh
    - ./bin/install-cgns.sh

script:
    - cd src
    - make
    - make install
    - cd tests
    - make
    - make test
    - cd ../examples/fortran
    - make
    - make test
    - cd ../../Test_UserGuideCode/Fortran_code
    - make
    - make test
    - cd ../C_code
    - make
    - make test
    
