language: C
sudo: required

os:
#  - linux
  - osx

# whitelist
branches:
  only:
    - develop

notifications:
  email: false

before_install:
    - ./install-hdf.sh
    - if [ "$(uname)" = "Linux" ]; then 
         sudo apt-get install gfortran; 
      fi
    - brew install gcc

script:
    - ./install-cgns.sh
    - cd src
    - make
    - cd tests
    - make
    - make test
