osx_image: xcode8.1
language: C
sudo: required

os:
  - osx
#  - linux

# whitelist
branches:
  only:
    - develop

notifications:
  email: false

before_install:
    - |
      if [ "$(uname)" = "Linux" ]; then
         sudo apt-get update -qq;
         sudo apt-get install -qq gfortran;
      fi
    - 'if [[ "$TRAVIS_OS_NAME" == "osx"]]; then brew install gcc; CC=gcc-5; FC=gfortran-5; F77=gfortran-5; fi'
    - ./bin/install-hdf.sh

before_script:
    - ./bin/install-cgns.sh

script:
    - cd src
    - make
    - make install
    - cd tests
    - make
    - make test
    - cd ../examples/fortran
    - make
    - make test
    - cd ../../Test_UserGuideCode/Fortran_code
    - make
    - make test
    - cd ../C_code
    - make
    - make test
    
