language: C

sudo: false

# whitelist
branches:
  only:
    - develop

notifications:
  email: false

before_install:
    - ./install-hdf.sh

install:
    - ./install-cgns.sh

#script:
#    - python setup.py build -f
#    - python setup.py test