osx_image: xcode8.1
language: C
sudo: required

#dist: trusty

# whitelist
branches:
  only:
    - develop

notifications:
  email: false

before_install:
    - |
      if [ "$(uname)" = "Linux" ]; then
         sudo apt-get update -qq;
         sudo apt-get install -qq gfortran;
      fi
    - test $(uname) = "Darwin" && brew update || true
    - test $(uname) = "Darwin" && brew tap homebrew/versions || true
    - test $(uname) = "Darwin" && brew install gcc6 || true

# Need to set the homebrew path to gcc, 

matrix:
   include:
#     - os: linux
#       compiler: gcc-4.9
#       install: export CC="gcc" export FC="gfortran" export F77="gfortran"
     - os: osx
       env: CCOMPILER=gcc-6 FCOMPILER=gfortran-6
       compiler: gcc-6
       install: export CC="gcc-6" export FC="gfortran-6" export F77="gfortran-6"

before_script:
    - ./bin/install-hdf.sh
    - ./bin/install-cgns.sh

script:
    - cd src
    - ls /usr/local/bin/gcc*
    - ls /usr/local/Cellar/gcc*
    - make
    - make install
    - cd tests
    - make
    - make test
    - cd ../examples/fortran
    - make
    - make test
    - cd ../../Test_UserGuideCode/Fortran_code
    - make
    - make test
    - cd ../C_code
    - make
    - make test
    
