language: C

#sudo: false

# whitelist
branches:
  only:
    - develop

notifications:
  email: false

before_install:
    - ./install-hdf.sh
    - sudo apt-get install gfortran
    - ./install-cgns.sh

#script:
#     - ./install-cgns.sh

install:
    - echo $PWD
    - ls
    - cd CGNS/src
    - echo $PWD
    - ls
    - make
    - make tests
