language: C
sudo: required

os:
#  - linux
  - osx

# whitelist
branches:
  only:
    - develop

notifications:
  email: false

before_install:
    - ./install-hdf.sh
#    - sudo apt-get install gfortran
    - brew install gfortran

script:
    - ./install-cgns.sh
    - cd src
    - make
    - cd tests
    - make
    - make test
